
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdvakfhmoaoucmhbhwvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkdmFrZmhtb2FvdWNtaGJod3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3OTI1OTEsImV4cCI6MjA1MDM2ODU5MX0.wvvxbqF3Hg_fmQ_4aJCqISQvcFXhm-2BngjvO6EHL0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storageKey: 'dealer_auth_token', // Custom storage key
      storage: localStorage, // Explicitly use localStorage for persistence
      flowType: 'pkce', // Use PKCE flow for better security
      debug: false // Disable debug logs
    },
    realtime: {
      params: {
        eventsPerSecond: 2 // Reduce realtime events to prevent 400 errors
      }
    },
    global: {
      // Add retries for fetch operations
      fetch: (url, options) => {
        return fetch(url, {
          ...options,
          // Add cache control to prevent stale responses
          headers: {
            ...options?.headers,
            'Cache-Control': 'no-cache'
          }
        });
      }
    }
  }
);
