
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdvakfhmoaoucmhbhwvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkdmFrZmhtb2FvdWNtaGJod3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3OTI1OTEsImV4cCI6MjA1MDM2ODU5MX0.wvvxbqF3Hg_fmQ_4aJCqISQvcFXhm-2BngjvO6EHL0M";

// Create a fetch implementation with consistent headers
const customFetch = (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const headers = new Headers(options?.headers || {});
  
  // Ensure apikey is always present
  if (!headers.has('apikey')) {
    headers.set('apikey', SUPABASE_PUBLISHABLE_KEY);
  }
  
  // Add authorization from localStorage if available with better error handling
  try {
    // Now use the correct storage key (dealer_auth_token)
    const currentSession = localStorage.getItem('dealer_auth_token');
    if (currentSession) {
      try {
        const session = JSON.parse(currentSession);
        if (session?.access_token && !headers.has('Authorization')) {
          headers.set('Authorization', `Bearer ${session.access_token}`);
          // Debug log to trace auth token during development
          if (import.meta.env.DEV) {
            const tokenPreview = session.access_token.substring(0, 10) + '...';
            console.debug(`Added auth token to request: ${tokenPreview}`);
          }
        } else if (!session?.access_token) {
          console.warn('Session exists but no access_token found');
        }
      } catch (parseError) {
        // This likely means the session is corrupted
        console.error('Failed to parse session JSON from localStorage', parseError);
        // Remove the corrupted session
        localStorage.removeItem('dealer_auth_token');
      }
    } else {
      console.debug('No auth session in localStorage for request to: ' + url.toString());
    }
  } catch (e) {
    console.error('Error accessing localStorage for auth token', e);
  }
  
  // Add cache control
  if (!headers.has('Cache-Control')) {
    headers.set('Cache-Control', 'no-cache');
  }
  
  // Add some debugging headers for dev mode
  if (import.meta.env.DEV) {
    headers.set('X-Client-Request-Time', new Date().toISOString());
  }
  
  return fetch(url, {
    ...options,
    headers,
    credentials: 'same-origin'
  });
};

// Create and export the supabase client
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storageKey: 'dealer_auth_token',
      storage: localStorage
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Content-Type': 'application/json'
      },
      fetch: customFetch
    },
    // Use retryOptions configuration
    db: {
      schema: 'public'
    },
    // Increase timeouts for edge functions
    realtime: {
      timeout: 20000
    }
  }
);

// Initialize client immediately to avoid lazy loading issues
(async () => {
  try {
    // Check for existing session and log its status
    const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
    
    if (sessionError) {
      console.warn('Supabase session check error:', sessionError.message);
      return;
    }
    
    if (sessionData && sessionData.session) {
      console.log('Session exists and expires at:', new Date(sessionData.session.expires_at! * 1000).toLocaleString());
      
      // Check if token is close to expiry
      const now = new Date();
      const expiresAt = new Date(sessionData.session.expires_at! * 1000);
      const timeUntilExpiry = expiresAt.getTime() - now.getTime();
      
      if (timeUntilExpiry < 60 * 60 * 1000) { // Less than 1 hour
        console.log('Session token will expire soon, refreshing...');
        try {
          await supabase.auth.refreshSession();
          console.log('Session token refreshed successfully');
        } catch (refreshError) {
          console.warn('Failed to refresh session token:', refreshError);
        }
      }
      
      // Only test connection to protected tables if we have an authenticated session
      try {
        const { error } = await supabase.from('dealers').select('count').limit(1);
        if (error) {
          console.warn('RLS check warning:', error.message);
          
          // Special handling for auth errors
          if (error.code === '401') {
            console.warn('Authentication error during initialization - token may be expired');
          } else if (error.code === '42501') {
            console.warn('Permission denied error - RLS policies may need configuration');
          }
        } else {
          console.log('Supabase client initialized successfully with database access');
        }
      } catch (err) {
        console.error('Error testing connection to dealers table:', err);
      }
    } else {
      console.log('No active session found - skipping protected table tests');
      console.log('Supabase client initialized successfully for unauthenticated access');
    }
  } catch (err) {
    console.error('Supabase client initialization error:', err);
  }
})();
